# https://hub.docker.com/r/library/node/tags/
image: node:latest
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#AWS access keys stored as secret variables
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#This declares the pipeline stages
stages:
  - build
  - test
  - deploy
cache:
  paths:
  - node_modules/
build:
  stage: build
  script:
    - npm install
    - npm run-script build
test:
  stage: test
  script:
    - echo "Running react test suite......"
deploy to s3:
    type: deploy
    image: srikoushik/aws-cli-node-docker
    script:
        - npm install
        - CI=false npm run build
        - sh sync.sh
    only:
        - master